### ISSUE TITLE
DMA Update Speed

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#37] opened 2022-08-25 11:42 UTC
Currently the DMA properties update slowly.
This behavior manifests as the properties freezing on incorrect values when an update occurs. This is because the memory locations have not been updated yet, Gamehook is still correctly polling every other values (other than the DMA values). After some amount of time (appears to be random right now) the memory addresses will be updated and the values begin updating as expected. When the next memory address update occurs this behavior repeats, usually with a different delay interval.

**Comment by Scotts-Thoughts** [comment] 2022-09-11 18:04
Resolved

**Comment by flamesage** [comment] 2022-09-11 18:06
The root cause of this issue actually was related to a bug with the data block processor. It was sending a change event every frame which was causing a slow down of DMA properties -- and properties in general. 

Resolving the bug in the spam of SignalR updates resolved this issue and resumed normal speed of messages.

**Closed by flamesage** 2022-09-11 18:06 UTC
Labels: bug
